version: "3.5"
services:
  elasticsearch:
    image: elasticsearch:7.3.2
    hostname: elasticsearch
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "/var/docker/elasticsearch/log:/usr/share/elasticsearch/logs"
      - "/var/docker/elasticsearch/data:/usr/share/elasticsearch/data"
    networks:
      - elasticsearchnet
    environment:
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
      - "discovery.type=single-node"
      - "node.name=node-1"
networks:
  elasticsearchnet:
    name: elasticsearchnet
