version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "/var/docker/${repository}/log:/usr/share/${repository}/logs"
      - "/var/docker/${repository}/data:/usr/share/${repository}/data"
    environment:
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
      - "discovery.type=single-node"
      - "node.name=node-1"
      - "network.host=0.0.0.0"
    networks:
      - online
networks:
  online:
    external: true
    name: online
